In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [3]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/AIProject/data.csv')
df.head()
df.shape

# df.info()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/tmp/ipykernel_77209/3589259448.py:5: DtypeWarning: Columns (29,30,31,32,33,34,35,36,37,38,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/AIProject/data.csv')

(5876178, 46)

In [4]:
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [5]:
df['Severity'].value_counts()
df['State'].value_counts()

df_Ca= df[df['State'] == 'CA']
df_Ca['Severity'].value_counts()

df_Ca.shape
# df_Ca['Astronomical_Twilight'].value_counts()

(1216105, 46)

In [6]:
columns= ['Severity', 'Start_Time', 'Start_Lat','Start_Lng',  'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Speed(mph)','Precipitation(in)', 'Weather_Condition',  'Crossing',  'Junction', 'Railway',  'Stop', 'Traffic_Signal', 'Sunrise_Sunset']

In [7]:
df_Ca.corr(numeric_only=True)['Severity'].sort_values()

Distance(mi)        -0.130617
Start_Lat           -0.114734
End_Lat             -0.004785
Visibility(mi)      -0.002224
End_Lng              0.011070
Wind_Chill(F)        0.016736
Wind_Speed(mph)      0.032472
Humidity(%)          0.034064
Temperature(F)       0.035308
Precipitation(in)    0.041409
Start_Lng            0.088234
Pressure(in)         0.115830
Severity             1.000000
Name: Severity, dtype: float64

In [8]:

df_Ca=df_Ca[columns]

In [9]:
df_Ca.notnull().sum()

Severity             1216105
Start_Time           1216105
Start_Lat            1216105
Start_Lng            1216105
Temperature(F)       1187097
Wind_Chill(F)         775979
Humidity(%)          1185458
Pressure(in)         1191953
Visibility(mi)       1189511
Wind_Speed(mph)      1082245
Precipitation(in)     752295
Weather_Condition    1190202
Crossing             1216105
Junction             1216105
Railway              1216105
Stop                 1216105
Traffic_Signal       1216105
Sunrise_Sunset       1214975
dtype: int64

In [10]:
df_Ca.drop(columns=['Wind_Chill(F)', 'Precipitation(in)'], inplace=True)

In [11]:
df_Ca.head()
df_Ca.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1216105 entries, 728 to 5876173
Data columns (total 16 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Severity           1216105 non-null  int64
 1   Start_Time         1216105 non-null  object
 2   Start_Lat          1216105 non-null  float64
 3   Start_Lng          1216105 non-null  float64
 4   Temperature(F)     1187097 non-null  float64
 5   Humidity(%)        1185458 non-null  float64
 6   Pressure(in)       1191953 non-null  float64
 7   Visibility(mi)     1189511 non-null  float64
 8   Wind_Speed(mph)    1082245 non-null  float64
 9   Weather_Condition  1190202 non-null  object
 10  Crossing           1216105 non-null  object
 11  Junction           1216105 non-null  object
 12  Railway            1216105 non-null  object
 13  Stop               1216105 non-null  object
 14  Traffic_Signal     1216105 non-null  object
 15  Sunrise_Sunset     1214975 non-null  object
dtypes: float64(7), int64(1), object(8)
memory usage: 157.7+ MB

In [12]:
df_Ca.fillna({
    'Temperature(F)': df_Ca['Temperature(F)'].mean(),
    'Humidity(%)': df_Ca['Humidity(%)'].mean(),
    'Pressure(in)': df_Ca['Pressure(in)'].mean(),
    'Visibility(mi)': df_Ca['Visibility(mi)'].mean(),
    'Wind_Speed(mph)': df_Ca['Wind_Speed(mph)'].mean()
},inplace=True)

In [13]:
df_Ca.notnull().sum()

Severity             1216105
Start_Time           1216105
Start_Lat            1216105
Start_Lng            1216105
Temperature(F)       1216105
Humidity(%)          1216105
Pressure(in)         1216105
Visibility(mi)       1216105
Wind_Speed(mph)      1216105
Weather_Condition    1190202
Crossing             1216105
Junction             1216105
Railway              1216105
Stop                 1216105
Traffic_Signal       1216105
Sunrise_Sunset       1214975
dtype: int64

In [14]:
df_Ca.fillna({
    'Weather_Condition': df_Ca['Weather_Condition'].mode()[0],
    'Sunrise_Sunset': df_Ca['Sunrise_Sunset'].mode()[0]
},inplace=True)

In [15]:
df_Ca['Start_Time'] = pd.to_datetime(df_Ca['Start_Time'], errors='coerce')
df_Ca['hour']= df_Ca['Start_Time'].dt.hour
df_Ca['day']= df_Ca['Start_Time'].dt.dayofweek
df_Ca['month']= df_Ca['Start_Time'].dt.month

In [16]:
df_Ca.sample(12)
df_Ca.notnull().sum()
df_Ca.fillna({
    'hour': df_Ca['hour'].mode()[0],
    'day': df_Ca['day'].mode()[0],
    'month': df_Ca['month'].mode()[0]
}, inplace=True)

In [17]:
df_Ca.notnull().sum()
df_Ca.drop(columns= ['Start_Time'], inplace=True)

In [18]:

df_Ca.notnull().sum()

Severity             1216105
Start_Lat            1216105
Start_Lng            1216105
Temperature(F)       1216105
Humidity(%)          1216105
Pressure(in)         1216105
Visibility(mi)       1216105
Wind_Speed(mph)      1216105
Weather_Condition    1216105
Crossing             1216105
Junction             1216105
Railway              1216105
Stop                 1216105
Traffic_Signal       1216105
Sunrise_Sunset       1216105
hour                 1216105
day                  1216105
month                1216105
dtype: int64

In [18]:
df_Ca.info()
df_Ca.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1216105 entries, 728 to 5876173
Data columns (total 18 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Severity           1216105 non-null  int64
 1   Start_Lat          1216105 non-null  float64
 2   Start_Lng          1216105 non-null  float64
 3   Temperature(F)     1216105 non-null  float64
 4   Humidity(%)        1216105 non-null  float64
 5   Pressure(in)       1216105 non-null  float64
 6   Visibility(mi)     1216105 non-null  float64
 7   Wind_Speed(mph)    1216105 non-null  float64
 8   Weather_Condition  1216105 non-null  object
 9   Crossing           1216105 non-null  object
 10  Junction           1216105 non-null  object
 11  Railway            1216105 non-null  object
 12  Stop               1216105 non-null  object
 13  Traffic_Signal     1216105 non-null  object
 14  Sunrise_Sunset     1216105 non-null  object
 15  hour               1216105 non-null  float64
 16  day                1216105 non-null  float64
 17  month              1216105 non-null  float64
dtypes: float64(10), int64(1), object(7)
memory usage: 176.3+ MB

,Severity,Start_Lat,Start_Lng,Temperature(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Weather_Condition,Crossing,Junction,Railway,Stop,Traffic_Signal,Sunrise_Sunset,hour,day,month
728,3,38.085300,-122.233017,75.0,48.0,30.00,10.0,5.8,Clear,False,False,False,False,False,Day,10.0,1.0,6.0
729,3,37.631813,-122.084167,75.0,48.0,30.06,10.0,4.6,Clear,False,False,False,False,False,Day,10.0,1.0,6.0
730,2,37.896564,-122.070717,82.9,31.0,29.97,10.0,4.6,Clear,False,False,False,False,False,Day,10.0,1.0,6.0
731,3,37.334255,-122.032471,75.9,48.0,30.04,10.0,4.6,Clear,False,False,False,False,False,Day,10.0,1.0,6.0
732,2,37.250729,-121.910713,75.2,41.0,30.06,10.0,5.8,Clear,False,False,False,False,False,Day,10.0,1.0,6.0

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

ohe= OneHotEncoder(handle_unknown='ignore',sparse_output=False)

In [20]:
cat_cols= ['Weather_Condition',  'Crossing',  'Junction', 'Railway',  'Stop', 'Traffic_Signal', 'Sunrise_Sunset']
preprocessor= ColumnTransformer(transformers=[
    ('cat', ohe, cat_cols)
], remainder= 'passthrough')

In [ ]:
# from sklearn.pipeline import Pipeline
# from sklearn.ensemble import RandomForestClassifier

# # from cuml.ensemble import RandomForestClassifier
# # from cuml.model_selection import train_test_split


# model= Pipeline(steps=[
#     ('preprocessor', preprocessor),
#     ('classifir', RandomForestClassifier(class_weight='balanced', random_state=42, n_estimators=100, n_jobs=-1))
# ])

# x= df_Ca.drop(columns=['Severity'])
# y= df_Ca['Severity']

In [ ]:
# score=[]

# for i in range(50):
#     x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=i)
#     model1= Pipeline(steps=[
#     ('preprocessor', preprocessor),
#     ('classifir', RandomForestClassifier())])
#     model1.fit(x_train, y_train)
#     score.append(model1.score(x_test, y_test))

In [ ]:
# import numpy as np
# np.argmax(score)

np.int64(1)

In [ ]:
# score[1]

0.7995156668215326

In [ ]:
# from sklearn.model_selection import train_test_split
# x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=1)
# model.fit(x_train, y_train)
# # model.score(x_test, y_test)

0.8300064550347215

In [ ]:
# from sklearn.metrics import classification_report, confusion_matrix
# y_pred= model.predict(x_test)
# print(classification_report(y_test, y_pred))
# print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.11      0.01      0.02       908
           2       0.85      0.95      0.90    189878
           3       0.69      0.42      0.52     51123
           4       0.67      0.30      0.41      1312

    accuracy                           0.83    243221
   macro avg       0.58      0.42      0.46    243221
weighted avg       0.81      0.83      0.81    243221

[[    12    887      9      0]
 [    98 180025   9580    175]
 [     3  29652  21448     20]
 [     0    811    111    390]]

In [1]:
print("Hello world")

Hello world

In [1]:
y1= df_Ca['Severity']-1
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix
x_train, x_test, y_train, y_test= train_test_split(x, y1, test_size=0.2, random_state=42)
model2 =Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifir', XGBClassifier(objective= 'multi:softmax', num_class= 4, n_estimators= 100,random_state= 42,learning_rate=0.1,subsample=0.8,colsample_bytree=0.8,))
]) 
model2.fit(x_train, y_train)
# y_pred= model2.predict(x_test)
model2.score(x_test, y_test)
y_prob = model2.predict_proba(x_test)[:, 1]
y_pred = (y_prob > 0.45).astype(int)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

NameError: name 'df_Ca' is not defined

In [ ]:
df_Ca['Severity'].value_counts()